// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using cs_se347.Model;

#nullable disable

namespace cs_se347.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231225041337_1.0.3")]
    partial class _103
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("cs_se347.Model.SqlAddress", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<string>("dia_chi_detail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("dia_chi_mac_dinh")
                        .HasColumnType("boolean");

                    b.Property<string>("ho_va_ten")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("phuong_xa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("quan_huyen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("so_dien_thoai")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("tinh_thanh_pho")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("userID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("userID");

                    b.ToTable("tb_address");
                });

            modelBuilder.Entity("cs_se347.Model.SqlCart", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<DateTime>("create_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("modified_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("shopID")
                        .HasColumnType("bigint");

                    b.Property<long>("userID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("shopID");

                    b.HasIndex("userID");

                    b.ToTable("tb_cart");
                });

            modelBuilder.Entity("cs_se347.Model.SqlCartItem", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<long?>("SqlOrderItemID")
                        .HasColumnType("bigint");

                    b.Property<long>("cartID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("create_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("modified_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("option")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("productID")
                        .HasColumnType("bigint");

                    b.Property<int>("quantity")
                        .HasColumnType("integer");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("SqlOrderItemID");

                    b.HasIndex("cartID");

                    b.HasIndex("productID");

                    b.ToTable("tb_cartItem");
                });

            modelBuilder.Entity("cs_se347.Model.SqlCategory", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("slug")
                        .HasColumnType("text");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("tb_category");
                });

            modelBuilder.Entity("cs_se347.Model.SqlOrder", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<long?>("addressID")
                        .HasColumnType("bigint");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("userID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("addressID");

                    b.HasIndex("userID");

                    b.ToTable("tb_order");
                });

            modelBuilder.Entity("cs_se347.Model.SqlOrderItem", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<long>("orderID")
                        .HasColumnType("bigint");

                    b.Property<long>("shopID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("orderID");

                    b.HasIndex("shopID");

                    b.ToTable("tb_orderItem");
                });

            modelBuilder.Entity("cs_se347.Model.SqlProduct", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<long>("categoryID")
                        .HasColumnType("bigint");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("detail")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("discount")
                        .HasColumnType("integer");

                    b.Property<int>("inventory")
                        .HasColumnType("integer");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("boolean");

                    b.Property<List<string>>("options")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("productImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("productListImage")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("productName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("productPrice")
                        .HasColumnType("bigint");

                    b.Property<long>("productSalePrice")
                        .HasColumnType("bigint");

                    b.Property<float>("rating")
                        .HasColumnType("real");

                    b.Property<long>("shopID")
                        .HasColumnType("bigint");

                    b.Property<int>("sold")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("categoryID");

                    b.HasIndex("shopID");

                    b.ToTable("tb_product");
                });

            modelBuilder.Entity("cs_se347.Model.SqlShop", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<string>("danh_gia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("logo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("rating")
                        .HasColumnType("double precision");

                    b.HasKey("ID");

                    b.ToTable("tb_shop");
                });

            modelBuilder.Entity("cs_se347.Model.SqlUser", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<string>("avatar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("fullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("tb_user");
                });

            modelBuilder.Entity("cs_se347.Model.SqlAddress", b =>
                {
                    b.HasOne("cs_se347.Model.SqlUser", "user")
                        .WithMany()
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("cs_se347.Model.SqlCart", b =>
                {
                    b.HasOne("cs_se347.Model.SqlShop", "shop")
                        .WithMany()
                        .HasForeignKey("shopID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("cs_se347.Model.SqlUser", "user")
                        .WithMany()
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("shop");

                    b.Navigation("user");
                });

            modelBuilder.Entity("cs_se347.Model.SqlCartItem", b =>
                {
                    b.HasOne("cs_se347.Model.SqlOrderItem", null)
                        .WithMany("list_cart_item")
                        .HasForeignKey("SqlOrderItemID");

                    b.HasOne("cs_se347.Model.SqlCart", "cart")
                        .WithMany("cart_items")
                        .HasForeignKey("cartID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("cs_se347.Model.SqlProduct", "product")
                        .WithMany()
                        .HasForeignKey("productID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cart");

                    b.Navigation("product");
                });

            modelBuilder.Entity("cs_se347.Model.SqlOrder", b =>
                {
                    b.HasOne("cs_se347.Model.SqlAddress", "address")
                        .WithMany()
                        .HasForeignKey("addressID");

                    b.HasOne("cs_se347.Model.SqlUser", "user")
                        .WithMany()
                        .HasForeignKey("userID");

                    b.Navigation("address");

                    b.Navigation("user");
                });

            modelBuilder.Entity("cs_se347.Model.SqlOrderItem", b =>
                {
                    b.HasOne("cs_se347.Model.SqlOrder", "order")
                        .WithMany("items")
                        .HasForeignKey("orderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("cs_se347.Model.SqlShop", "shop")
                        .WithMany()
                        .HasForeignKey("shopID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("order");

                    b.Navigation("shop");
                });

            modelBuilder.Entity("cs_se347.Model.SqlProduct", b =>
                {
                    b.HasOne("cs_se347.Model.SqlCategory", "category")
                        .WithMany()
                        .HasForeignKey("categoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("cs_se347.Model.SqlShop", "shop")
                        .WithMany("products")
                        .HasForeignKey("shopID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");

                    b.Navigation("shop");
                });

            modelBuilder.Entity("cs_se347.Model.SqlCart", b =>
                {
                    b.Navigation("cart_items");
                });

            modelBuilder.Entity("cs_se347.Model.SqlOrder", b =>
                {
                    b.Navigation("items");
                });

            modelBuilder.Entity("cs_se347.Model.SqlOrderItem", b =>
                {
                    b.Navigation("list_cart_item");
                });

            modelBuilder.Entity("cs_se347.Model.SqlShop", b =>
                {
                    b.Navigation("products");
                });
#pragma warning restore 612, 618
        }
    }
}
